// content/logos.ts
// AUTO-GENERATED by scripts/generate-logos.mjs — do not edit by hand.
// Regenerate with: node scripts/generate-logos.mjs
// Source: public/Logos

export type LogoAsset = {
  id: string;
  filename: string;
  src: string;
  alt: string;
};

export const LOGOS: LogoAsset[] = [
  {
    "id": "screenshot-2026-09-30-180131",
    "filename": "Screenshot 2026-09-30 180131.png",
    "src": "/Logos/clean/Screenshot%202026-09-30%20180131.png",
    "alt": "KCATCH client logo 1"
  },
  {
    "id": "screenshot-2026-09-30-180135",
    "filename": "Screenshot 2026-09-30 180135.png",
    "src": "/Logos/clean/Screenshot%202026-09-30%20180135.png",
    "alt": "KCATCH client logo 2"
  },
  {
    "id": "screenshot-2026-09-30-180149",
    "filename": "Screenshot 2026-09-30 180149.png",
    "src": "/Logos/clean/Screenshot%202026-09-30%20180149.png",
    "alt": "KCATCH client logo 3"
  },
  {
    "id": "screenshot-2026-09-30-180154",
    "filename": "Screenshot 2026-09-30 180154.png",
    "src": "/Logos/clean/Screenshot%202026-09-30%20180154.png",
    "alt": "KCATCH client logo 4"
  },
  {
    "id": "screenshot-2026-09-30-180203",
    "filename": "Screenshot 2026-09-30 180203.png",
    "src": "/Logos/clean/Screenshot%202026-09-30%20180203.png",
    "alt": "KCATCH client logo 5"
  },
  {
    "id": "screenshot-2026-09-30-180211",
    "filename": "Screenshot 2026-09-30 180211.png",
    "src": "/Logos/clean/Screenshot%202026-09-30%20180211.png",
    "alt": "KCATCH client logo 6"
  },
  {
    "id": "screenshot-2026-09-30-180215",
    "filename": "Screenshot 2026-09-30 180215.png",
    "src": "/Logos/clean/Screenshot%202026-09-30%20180215.png",
    "alt": "KCATCH client logo 7"
  },
  {
    "id": "screenshot-2026-09-30-180219",
    "filename": "Screenshot 2026-09-30 180219.png",
    "src": "/Logos/clean/Screenshot%202026-09-30%20180219.png",
    "alt": "KCATCH client logo 8"
  },
  {
    "id": "screenshot-2026-09-30-180224",
    "filename": "Screenshot 2026-09-30 180224.png",
    "src": "/Logos/clean/Screenshot%202026-09-30%20180224.png",
    "alt": "KCATCH client logo 9"
  },
  {
    "id": "screenshot-2026-09-30-180229",
    "filename": "Screenshot 2026-09-30 180229.png",
    "src": "/Logos/clean/Screenshot%202026-09-30%20180229.png",
    "alt": "KCATCH client logo 10"
  },
  {
    "id": "screenshot-2026-09-30-180233",
    "filename": "Screenshot 2026-09-30 180233.png",
    "src": "/Logos/clean/Screenshot%202026-09-30%20180233.png",
    "alt": "KCATCH client logo 11"
  },
  {
    "id": "screenshot-2026-09-30-180240",
    "filename": "Screenshot 2026-09-30 180240.png",
    "src": "/Logos/clean/Screenshot%202026-09-30%20180240.png",
    "alt": "KCATCH client logo 12"
  },
  {
    "id": "screenshot-2026-09-30-180247",
    "filename": "Screenshot 2026-09-30 180247.png",
    "src": "/Logos/clean/Screenshot%202026-09-30%20180247.png",
    "alt": "KCATCH client logo 13"
  },
  {
    "id": "screenshot-2026-09-30-180251",
    "filename": "Screenshot 2026-09-30 180251.png",
    "src": "/Logos/clean/Screenshot%202026-09-30%20180251.png",
    "alt": "KCATCH client logo 14"
  },
  {
    "id": "screenshot-2026-09-30-180257",
    "filename": "Screenshot 2026-09-30 180257.png",
    "src": "/Logos/clean/Screenshot%202026-09-30%20180257.png",
    "alt": "KCATCH client logo 15"
  },
  {
    "id": "screenshot-2026-09-30-180301",
    "filename": "Screenshot 2026-09-30 180301.png",
    "src": "/Logos/clean/Screenshot%202026-09-30%20180301.png",
    "alt": "KCATCH client logo 16"
  },
  {
    "id": "screenshot-2026-09-30-180305",
    "filename": "Screenshot 2026-09-30 180305.png",
    "src": "/Logos/clean/Screenshot%202026-09-30%20180305.png",
    "alt": "KCATCH client logo 17"
  },
  {
    "id": "screenshot-2026-09-30-180308",
    "filename": "Screenshot 2026-09-30 180308.png",
    "src": "/Logos/clean/Screenshot%202026-09-30%20180308.png",
    "alt": "KCATCH client logo 18"
  },
  {
    "id": "screenshot-2026-09-30-180313",
    "filename": "Screenshot 2026-09-30 180313.png",
    "src": "/Logos/clean/Screenshot%202026-09-30%20180313.png",
    "alt": "KCATCH client logo 19"
  },
  {
    "id": "screenshot-2026-09-30-180318",
    "filename": "Screenshot 2026-09-30 180318.png",
    "src": "/Logos/clean/Screenshot%202026-09-30%20180318.png",
    "alt": "KCATCH client logo 20"
  },
  {
    "id": "screenshot-2026-09-30-180323",
    "filename": "Screenshot 2026-09-30 180323.png",
    "src": "/Logos/clean/Screenshot%202026-09-30%20180323.png",
    "alt": "KCATCH client logo 21"
  },
  {
    "id": "screenshot-2026-09-30-180326",
    "filename": "Screenshot 2026-09-30 180326.png",
    "src": "/Logos/clean/Screenshot%202026-09-30%20180326.png",
    "alt": "KCATCH client logo 22"
  },
  {
    "id": "screenshot-2026-09-30-180330",
    "filename": "Screenshot 2026-09-30 180330.png",
    "src": "/Logos/clean/Screenshot%202026-09-30%20180330.png",
    "alt": "KCATCH client logo 23"
  },
  {
    "id": "screenshot-2026-09-30-180334",
    "filename": "Screenshot 2026-09-30 180334.png",
    "src": "/Logos/clean/Screenshot%202026-09-30%20180334.png",
    "alt": "KCATCH client logo 24"
  },
  {
    "id": "screenshot-2026-09-30-180337",
    "filename": "Screenshot 2026-09-30 180337.png",
    "src": "/Logos/clean/Screenshot%202026-09-30%20180337.png",
    "alt": "KCATCH client logo 25"
  },
  {
    "id": "screenshot-2026-09-30-180340",
    "filename": "Screenshot 2026-09-30 180340.png",
    "src": "/Logos/clean/Screenshot%202026-09-30%20180340.png",
    "alt": "KCATCH client logo 26"
  },
  {
    "id": "screenshot-2026-09-30-180343",
    "filename": "Screenshot 2026-09-30 180343.png",
    "src": "/Logos/clean/Screenshot%202026-09-30%20180343.png",
    "alt": "KCATCH client logo 27"
  },
  {
    "id": "screenshot-2026-09-30-180346",
    "filename": "Screenshot 2026-09-30 180346.png",
    "src": "/Logos/clean/Screenshot%202026-09-30%20180346.png",
    "alt": "KCATCH client logo 28"
  },
  {
    "id": "screenshot-2026-09-30-180351",
    "filename": "Screenshot 2026-09-30 180351.png",
    "src": "/Logos/clean/Screenshot%202026-09-30%20180351.png",
    "alt": "KCATCH client logo 29"
  },
  {
    "id": "screenshot-2026-09-30-180356",
    "filename": "Screenshot 2026-09-30 180356.png",
    "src": "/Logos/clean/Screenshot%202026-09-30%20180356.png",
    "alt": "KCATCH client logo 30"
  },
  {
    "id": "screenshot-2026-09-30-180359",
    "filename": "Screenshot 2026-09-30 180359.png",
    "src": "/Logos/clean/Screenshot%202026-09-30%20180359.png",
    "alt": "KCATCH client logo 31"
  },
  {
    "id": "screenshot-2026-09-30-180403",
    "filename": "Screenshot 2026-09-30 180403.png",
    "src": "/Logos/clean/Screenshot%202026-09-30%20180403.png",
    "alt": "KCATCH client logo 32"
  },
  {
    "id": "screenshot-2026-09-30-180407",
    "filename": "Screenshot 2026-09-30 180407.png",
    "src": "/Logos/clean/Screenshot%202026-09-30%20180407.png",
    "alt": "KCATCH client logo 33"
  },
  {
    "id": "screenshot-2026-09-30-180410",
    "filename": "Screenshot 2026-09-30 180410.png",
    "src": "/Logos/clean/Screenshot%202026-09-30%20180410.png",
    "alt": "KCATCH client logo 34"
  },
  {
    "id": "screenshot-2026-09-30-180415",
    "filename": "Screenshot 2026-09-30 180415.png",
    "src": "/Logos/clean/Screenshot%202026-09-30%20180415.png",
    "alt": "KCATCH client logo 35"
  },
  {
    "id": "screenshot-2026-09-30-180418",
    "filename": "Screenshot 2026-09-30 180418.png",
    "src": "/Logos/clean/Screenshot%202026-09-30%20180418.png",
    "alt": "KCATCH client logo 36"
  },
  {
    "id": "screenshot-2026-09-30-180422",
    "filename": "Screenshot 2026-09-30 180422.png",
    "src": "/Logos/clean/Screenshot%202026-09-30%20180422.png",
    "alt": "KCATCH client logo 37"
  },
  {
    "id": "screenshot-2026-09-30-180424",
    "filename": "Screenshot 2026-09-30 180424.png",
    "src": "/Logos/clean/Screenshot%202026-09-30%20180424.png",
    "alt": "KCATCH client logo 38"
  },
  {
    "id": "screenshot-2026-09-30-180428",
    "filename": "Screenshot 2026-09-30 180428.png",
    "src": "/Logos/clean/Screenshot%202026-09-30%20180428.png",
    "alt": "KCATCH client logo 39"
  },
  {
    "id": "screenshot-2026-09-30-180430",
    "filename": "Screenshot 2026-09-30 180430.png",
    "src": "/Logos/clean/Screenshot%202026-09-30%20180430.png",
    "alt": "KCATCH client logo 40"
  },
  {
    "id": "screenshot-2026-09-30-180435",
    "filename": "Screenshot 2026-09-30 180435.png",
    "src": "/Logos/clean/Screenshot%202026-09-30%20180435.png",
    "alt": "KCATCH client logo 41"
  },
  {
    "id": "screenshot-2026-09-30-180439",
    "filename": "Screenshot 2026-09-30 180439.png",
    "src": "/Logos/clean/Screenshot%202026-09-30%20180439.png",
    "alt": "KCATCH client logo 42"
  }
];
