// This file is auto-generated. Do not edit.
export const assetManifest = new Set([
  "/file.svg",
  "/globe.svg",
  "/Images/BG Images/LandingPageBg.png",
  "/Images/BG Images/LandingPageBg.webp",
  "/Images/logo/Kcatch-logo.png",
  "/Images/PNGs/Banana man Left.png",
  "/Images/PNGs/Finger image tilt right.png",
  "/Images/PNGs/Flying Plane.png",
  "/Images/PNGs/Loudspeaker.png",
  "/Images/PNGs/PaperEffectBottom.cropped.png",
  "/Images/PNGs/PaperEffectBottom.png",
  "/Images/PNGs/PaperEffectTop.cropped.png",
  "/Images/PNGs/PaperEffectTop.png",
  "/Images/PNGs/Sleeping Cup.png",
  "/Images/PNGs/Swag hand.png",
  "/Images/Projects/01-Razorpay.webp",
  "/Images/Projects/02-Zee5.webp",
  "/Images/Projects/03-RummyCircle.webp",
  "/Images/Projects/03-RummyCircle-Large.png",
  "/Images/Projects/04-Qatar Airways.webp",
  "/Images/Projects/05-My11Circle.webp",
  "/Images/Projects/06-Pokerbazi.webp",
  "/Images/Projects/07-Azorte.webp",
  "/Images/Projects/08-Music Video.webp",
  "/Images/Projects/09-Influencers.webp",
  "/Images/Projects/10-Hebron.webp",
  "/Images/Projects/11-Kcartcaay.webp",
  "/Images/SS/Contact.png",
  "/Images/SS/Home (iPhone 15 Pro Max).png",
  "/Images/SS/Home Page.png",
  "/Images/SS/Projects.png",
  "/next.svg",
  "/vercel.svg",
  "/window.svg"
]);
