// scripts/generate-logos.mjs
// Scans public/Logos and (re)generates content/logos.ts — the list of
// client logo assets used by the "OUR FAMILY" DriftWall. Re-run this
// (`node scripts/generate-logos.mjs`) whenever files are added to/removed
// from public/Logos.

import { readdirSync, writeFileSync, existsSync } from "fs";
import { fileURLToPath } from "url";
import path from "path";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const logosDir = path.join(__dirname, "..", "public", "Logos");
const cleanDir = path.join(logosDir, "clean");
const outFile = path.join(__dirname, "..", "content", "logos.ts");

const VALID_EXTENSIONS = new Set([".png", ".jpg", ".jpeg", ".svg", ".webp", ".gif", ".avif"]);

function slugify(filename) {
  return path
    .parse(filename)
    .name.toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

const files = readdirSync(logosDir)
  .filter((f) => VALID_EXTENSIONS.has(path.extname(f).toLowerCase()))
  .sort();

// Prefer the transparent-background cutout in public/Logos/clean/<filename>
// (see scripts/clean-logos.mjs) when one exists; otherwise fall back to the
// untouched original in public/Logos/.
const entries = files.map((filename, i) => {
  const id = slugify(filename) || `logo-${i + 1}`;
  const hasClean = existsSync(path.join(cleanDir, filename));
  const src = hasClean
    ? `/Logos/clean/${encodeURIComponent(filename)}`
    : `/Logos/${encodeURIComponent(filename)}`;
  return { id, filename, src, alt: `KCATCH client logo ${i + 1}` };
});

const header = `// content/logos.ts
// AUTO-GENERATED by scripts/generate-logos.mjs — do not edit by hand.
// Regenerate with: node scripts/generate-logos.mjs
// Source: public/Logos

export type LogoAsset = {
  id: string;
  filename: string;
  src: string;
  alt: string;
};

export const LOGOS: LogoAsset[] = ${JSON.stringify(entries, null, 2)};
`;

writeFileSync(outFile, header);
console.log(`Wrote ${entries.length} logo entries to ${path.relative(process.cwd(), outFile)}`);
